name: Python v3.14 Build

on: [ workflow_dispatch ]

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        cache: 'pip' # Automatically caches dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: python -m PyInstaller main.spec

    - name: Prepare Artifacts
      run: |
        dir dist\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Simpler-FileBot-EXE
        path: dist/
        include-hidden-files: true
        if-no-files-found: error # Ensures the workflow fails if the EXE isn't found
